Backup/OrderSystemWeb/Controllers/CustomerController.cs
using Kotacs.Libraries.SOA.Contracts.Data;
using Kotacs.Libraries.SOA.Contracts.Services;
using Kotacs.Libraries.SOA.Proxies;
using Kotacs.Libraries.Web.Extensibility;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace OrderSystemWeb.Controllers
{
    public class CustomerController : KotacsControllerBase
    {
        //
        // GET: /Customer/
        private ICustomerService customerservice= default(ICustomerService);
        public CustomerController(ICustomerService customerservice)
        {
            this.customerservice = customerservice;
            //customerservice = new CustomerServiceProxy();
        }
        public ActionResult Index()
        {
            if (customerservice != default(ICustomerService))
            {
                var customers = customerservice.GetAllCustomers();
                return View(model: customers);
            }
            return View(viewName: "Error");
        }
        [ActionName("Details")]
        public ActionResult GetCustomerDetails(string customerid)
        {
            if (customerservice != default(ICustomerService))
            {
                var customers = customerservice.GetAllCustomers();
                var filteredCustomer = customers.Where(customer => customer.Customerid.Equals(customerid)).FirstOrDefault();
                if (filteredCustomer != default(Customer))
                {
                    ViewBag.customerid = customerid;
                    return View(model: filteredCustomer);
                }

            }
            return View(viewName:"Error");
        }
        [ActionName("Search")]
        public ActionResult GetFilteredCustomers(string customerName)
        {
            if (customerservice != default(ICustomerService) &&
                !string.IsNullOrEmpty(customerName))
            {
                var filteredCustomers = customerservice.GetCustomers(customerName);

                return View(viewName: "Index", model: filteredCustomers);
            }

            return View(viewName: "Error");
        }
        [ActionName("New")]
        public ActionResult InitializeCustomer()
        {
            var customer = new Customer { Customerid = "C" + new Random().Next(2000000).ToString() };
            return View(model: customer);

        }

        //[ActionName("SaveCustomer")]
        [ActionName("New")]
        [HttpPost]
        public ActionResult SaveCustomer(
            ////[Bind(Prefix="Thomson")]// if we are maintain a same prefix of all controls in form
            //[ModelBinder(typeof(CustomerModelBinder))]
            Customer customer)
        {
            customerservice.InsertCustomer(customer);
            //return View(viewName: "SaveCustomer");

            if (customer.CustomerName.Length <= 5)
                ModelState.AddModelError("CustomerName", "Customer name is not valid");
            return View(model: customer);

        }
        public ActionResult AjaxIndex()
        {
            return View();
        }

        [ActionName("LoadCustomers")]
        public ActionResult GetCustomers()
        {
            if (customerservice != default(ICustomerService))
            {
                var customers = customerservice.GetAllCustomers();
                ViewData.Model = customers;
                if (Request.IsAjaxRequest())
                    return PartialView();
                return View();
            }
                return View(viewName: "Error");
        }

        public ActionResult CustomerDetails(string customerId)
        {
            if (customerservice != default(ICustomerService))
            {
                var customers = customerservice.GetAllCustomers();
                var filteredCustomer = customers.Where(customer => customer.Customerid.Equals(customerId)).FirstOrDefault();
                if (filteredCustomer != default(Customer))
                {
                    ViewData.Model = filteredCustomer;
                    Thread.Sleep(200);
                    if (Request.IsAjaxRequest())
                        return PartialView();

                    return View();
                }
            }
            return View(viewName: "Error");            
        }
        [ActionName("Stock")]
        public ActionResult GetCurrentStock(string customerId)
        {
            var data = string.Format(@"Customer {0} Stock Value {1}",
                customerId, new Random().Next(200));

            var scriptOutput = string.Format(
                "javascript:processResult('{0}')", data);

            return JavaScript(scriptOutput);
        }
        public ActionResult AllCustomers()
        {
            if (customerservice != default(ICustomerService))
            {
                var customers = customerservice.GetAllCustomers();
                return Json(customers, JsonRequestBehavior.AllowGet);
            }
            return View(viewName: "Error");
        }
    }
}

Backup/OrderSystemWeb/Controllers/RedirectController.cs
using Kotacs.Libraries.Web.Extensibility;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.SessionState;
namespace OrderSystemWeb.Controllers
{
    [SessionState(SessionStateBehavior.Disabled)]
    public class RedirectController : KotacsControllerBase
    {
        //
        // GET: /Redirect/
       
        public ActionResult Index()
        {
            ViewData["IndexViewData"] = "From Index Action ViewData";
            ViewBag.ViewBagIndexMessage = "From Index Action ViewBag";
            TempData["IndexViewTempData"] = "From Index Action Temp ViewData";
            return View();
        }
        public ActionResult Action2()
        {
            ViewData["Action2ViewData"] = "From Action2 Action ViewData";
            ViewBag.ViewBagAction2Message = "From Action2 Action ViewBag";
            TempData["Action2ViewTempData"] = "From Action2 Action Temp ViewData";
            return RedirectToAction("Index");
        }
        //demonstrate the Action3 view cannot hold TempData (Peek) as it will be flagged to deletable in Action2, so will make use of Peek() to read and extend one more time
        
        public ActionResult Action3()
        {
            return View();
        }
    }
}

Backup/OrderSystemWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>Kotacs Web Hosting</title>
<meta name="description" content="" />
<meta name="keywords" content="" />
@*<link href="style.css" rel="stylesheet" type="text/css" />*@
    <link href="../../Content/Style.css" rel="stylesheet" />
</head>
<body>
<div id="header">
	<div id="logo">
		<h1><span><a href="#">Professional</a></span></h1>
	</div>
	<div id="menu">
		<ul>
			<li class="first">
             @Html.ActionLink("Home","Index")
			</li>
            <li>
                @Html.ActionLink("Customers","Index","Customer")
            </li>
            <li>
                @Html.ActionLink("Redirections","Index","Redirect")
            </li>
			@*<li><a href="#">Products</a></li>*@
            <li> @Html.ActionLink("Helpers","AjaxIndex","Customer")
            </li>
             <li> @Html.ActionLink("ARCustom","Index","ARCustom")
            </li>

		</ul>
	</div>
</div>
<div id="headershadow"><a href="#"><img src="../../Content/Images/header-picture.jpg" alt="" width="877" height="150" /></a></div>
<div id="content">
    @RenderBody()

    @RenderSection("Sidebar",required:false)
	<div style="clear: both;">&nbsp;</div>
</div>
<div id="footer">
	<!-- Please leave the link to http://www.100webhosting.com intact -->
	<p>
		&copy; 2013 kotacs.com. Design by <a href="http://www.kotacs.com/">Kotacs.com</a>.
	</p>
</div>
</body>
</html>